---
title: "R Control Flow Statements: Building blocks for automated Decision Making"
shorttitle: "R Control"
# Set names and affiliations.
# It is nice to specify everyone's orcid, if possible.
# There can be only one corresponding author, but declaring one is optional.
author:
  - name: Hoda Haeri (Matriculation:400963829)
    corresponding: true
    email: haeri.hoda@stud.hs-fresenius.de
    url:
    affiliations:
        name: "Hochschule Fresenius - University of Applied Science"
        group: "International Management, M.A."
        department:
        address:
        city: Köln
blank-lines-above-author-note: 2
author-note:
  status-changes:
    # Example: [Author name] is now at [affiliation].
    affiliation-change:
    # Example: [Author name] is deceased.
    deceased: ~
  # Disclosures condensed to one paragraph, but you can start a field with two line breaks to break them up: \n\nNew Paragraph
  disclosures:
    # Example: This study was registered at X (Identifier Y).
    study-registration: ~
    # Acknowledge and cite data/materials to be shared.
    data-sharing: ~
    # Example: This article is based on data published in [Reference].
    # Example: This article is based on the dissertation completed by [citation]. 
    related-report: ~
    # Example: [Author name] has been a paid consultant for Corporation X, which funded this study.
    conflict-of-interest: The authors have no conflicts of interest to disclose.
    # Example: This study was supported by Grant [Grant Number] from [Funding Source].
    financial-support: ~
    # Example: The authors are grateful to [Person] for [Reason].
    gratitude: ~
    # Example. Because the authors are equal contributors, order of authorship was determined by a fair coin toss.
    authorship-agreements: ~
abstract: "R is a powerful programming language widely used for data analysis and visualization. Control flow statements in R—such as if, else, for, while, and repeat—allow users to automate decision-making and repetitive tasks. These statements are the core building blocks that enable scripts to respond to data, adapt to changing situations, and streamline complex analytical processes. This document provides a clear overview of the main control flow statements in R, their syntax, and practical examples to illustrate their role in automating decision-making."

keywords: [ R programming,Control flow statements,Automation, Data analysis, Decision-making ] 
 

# If true, tables and figures are mingled with the text instead of listed at the end of the document.
impact-statement: ~
floatsintext: true
# Numbered lines (.pdf and .docx only)
numbered-lines: false
# File with references
bibliography: bibliography.bib
csl: apa.csl
# Suppress title page
suppress-title-page: false
# Link citations to references
link-citations: true
# Masks references that appear in the masked-citations list
mask: false
masked-citations:
# If true, adds today's date below author affiliations. If text, can be any value.
# This is not standard APA format, but it is convenient.
# Works with docx, html, and typst.
draft-date: false
# Language options. See https://quarto.org/docs/authoring/language.html
lang: en-US
language:
  citation-last-author-separator: "and"
  citation-masked-author: "Masked Citation"
  citation-masked-date: "n.d."
  citation-masked-title: "Masked Title"
  email: "Email"
  title-block-author-note: "Author Note"
  title-block-correspondence-note: "Correspondence concerning this article should be addressed to"
  title-block-role-introduction: "Author roles were classified using the Contributor Role Taxonomy (CRediT; [credit.niso.org]([https://credit.niso.org)]https://credit.niso.org)) as follows:"
  title-impact-statement: "Impact Statement"
  references-meta-analysis: "References marked with an asterisk indicate studies included in the meta-analysis."
format:
  apaquarto-html:
    toc: true
    theme: cosmo
    echo: true
    css: styles.css
  apaquarto-typst:
    keep-typ: true
    list-of-figures: false
    list-of-tables: false
    toc: true
    papersize: "us-letter"
  apaquarto-pdf:
    # Can be jou (journal), man (manuscript), stu (student), or doc (document)
    toc: true
    documentmode: man
    keep-tex: true
echo: true
---

**R** is a widely used language for statistical analysis, data manipulation, and visualization. One of its most powerful features is the ability to automate decisions and repetitive tasks through control flow statements, such as if, else, for, while, and repeat. These statements act like logic gates in a program, directing how and when different parts of the code are executed, based on specific conditions or data values. This approach allows R scripts to efficiently manage various types of data, respond to unexpected situations like missing values, and repeat processes without manual effort, making analysis more robust and scalable 


**What Are Control Flow Statements in R?**

Control flow statements in R work much like traffic signals, determining which sections of code should run, depending on the data or situation. By using these statements, programs can automatically make decisions, choose different paths of analysis, and repeat tasks as needed. This makes R code not only dynamic and efficient but also reliable, even when faced with real-world data challenges 


**Types of Control Flow Statements**


1- If, Else If, and Else Statements:

**If** statements execute a block of code only if a specified condition is true.

**Else** statements execute **if** the if condition is false.

**Else if** statements check further conditions if the previous ones are not met.

2- Repeat Loops:

Repeat loops execute a block of code multiple times until a certain condition is met, using a break statement to stop the loop.

3- While Loops:

While loops continue to run as long as a specific condition remains true, making them useful for processing unknown or varying amounts of data.

4- For Loops:

For loops repeat a block of code a set number of times, usually once for each value in a vector or list, making them ideal for systematic, repeated tasks.


**Why Are Control Flow Statements Important?**

Control flow statements are essential for making R scripts flexible, automated, and intelligent. They enable automation in common tasks such as data cleaning, handling missing values, and applying decision rules. This means R can process and analyze data on its own, reducing the need for manual oversight


**Conclusion**

Control flow statements are the building blocks that transform simple R scripts into dynamic, responsive tools. By using statements like if, else, for, while, and repeat, R users can automate decisions and repetitive processes, making their data analysis workflows more powerful and efficient. This adaptability is crucial for real-world data analysis, where data and requirements often change 



# References

<!-- References will auto-populate in the refs div below -->

::: {#refs}
:::

# Affidavit

I hereby affirm that this submitted paper was authored unaided and solely by me. Additionally, no other sources than those in the reference list were used. Parts of this paper, including tables and figures, that have been taken either verbatim or analogously from other works have in each case been properly cited with regard to their origin and authorship. This paper either in parts or in its entirety, be it in the same or similar form, has not been submitted to any other examination board and has not been published.

I acknowledge that the university may use plagiarism detection software to check my thesis. I agree to cooperate with any investigation of suspected plagiarism and to provide any additional information or evidence requested by the university.

Checklist:

-   [x] The handout contains 3-5 pages of text.
-   [x] The submission contains the Quarto file of the handout.
-   [x] The submission contains the Quarto file of the presentation.
-   [x] The submission contains the HTML file of the handout.
-   [x] The submission contains the HTML file of the presentation.
-   [x] The submission contains the PDF file of the handout.
-   [x] The submission contains the PDF file of the presentation.
-   [x] The title page of the presentation and the handout contain personal details (name, email, matriculation number).
-   [x] The handout contains a abstract.
-   [x] The presentation and the handout contain a bibliography, created using BibTeX with APA citation style.
-   [x] Either the handout or the presentation contains R code that proof the expertise in coding.
-   [x] The handout includes an introduction to guide the reader and a conclusion summarizing the work and discussing potential further investigations and readings, respectively.
-   [x] All significant resources used in the report and R code development.
-   [x] The filled out Affidavit.
-   [x] A concise description of the successful use of Git and GitHub, as detailed here: <https://github.com/hubchev/make_a_pull_request>.
-   [x] The link to the presentation and the handout published on GitHub.

\[Hoda Haeri,\] \[06/18/2025,\] \[Köln\]


